"""
Created by (Esteban Gómez) in  ${2022}
"""
"""Create a function that generates a random password. The password generated by the function
must have the following characteristics:
a. Length between 8 and 12 characters
b. Use at least one uppercase character, a number and a symbol. The function must be able to
generate passwords containing more than one character of these types, not just a single one
of each type."""

print("Your random password is:")

def random_password():
    "@prints a random password"
    import random
    import string
    length = random.randint(8, 12)
    keep_going=False
    password = []
    check1, check2, check3 = 0, 0, 0  # To check the conditions
    while keep_going==False:
        password.clear()
        while len(password)!=length:
            luck=random.randint(1,4)
            if luck==1:
                letter=random.choice(string.ascii_letters)
                password.append(letter)
            if luck==2:
                number= random.randint(0,9)
                check2=1
                password.append(number)
            if luck==3:
                symbol=random.choice(string.punctuation)
                check3=1
                password.append(symbol)
            if luck==4:
                upper_letter = random.choice(string.ascii_letters)
                upper_letter= upper_letter.upper()
                check1 = 1
                password.append(upper_letter)
        if len(password) == length:
            if check1==1 and check2==1 and check3==1:
                keep_going=True
    return password


for i in random_password():
    print(i,end="")